name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload built binary
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: pwacc # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/release/autoconnectcontroller
