name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - run: sudo apt-get -y install librust-pango-dev libgtk-4-dev libadwaita-1-dev libpipewire-0.3-dev libspa-0.2-dev libclang-dev rustc cargo
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: Upload built binary
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: pwacc # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/release/autoconnectcontroller
